EXCH = {'AM': 'JR', 'E': 'NA', 'AS': 'NA', 'AX': 'AU', 'BH': 'BI', 'BC': 'SM', 'MC': 'SM', 'BY': 'LB', 'BE': 'GR',
        'BN': 'SW', 'BI': 'SM',
        'BO': 'IN', 'B': 'US', 'BM': 'GR', 'BR': 'BB', 'CL': 'IN', 'V': 'CN', 'W': 'UV', 'MW': 'US', 'CE': 'CI',
        'C': 'US', 'CM': 'SL',
        'CO': 'DC', 'DL': 'IN', 'QA': 'QD', 'DU': 'UH', 'D': 'GR', 'd': 'GR', 'Z': 'SW', 'F': 'GR', 'FU': 'JP',
        'H': 'GR', 'HA': 'GR',
        'HE': 'FH', 'HK': 'HK', 'IS': 'TI', 'JK': 'IJ', 'Q': 'JP', 'J': 'SJ', 'KA': 'PA', 'KQ': 'KS', 'KS': 'KS',
        'KL': 'MK', 'KW': 'KK',
        'KY': 'JP', 'LG': 'NL', 'LA': 'SM', 'LN': 'FP', 'LM': 'PE', 'LS': 'PL', 'L': 'LN', 'LU': 'LX', 'MD': 'IN',
        'MA': 'SM', 'MC': 'SM',
        'ML': 'CB', 'MX': 'MM', 'MI': 'IM', 'p': 'FP', 'M': 'CN', 'MM': 'RM', 'MO': 'RM', 'MU': 'GR', 'OM': 'OM',
        'NG': 'JP', 'NR': 'KN',
        'O': 'US', 'OB': 'US', 'OJ': 'JP', 'NS': 'IN', 'N': 'US', 'NZ': 'NZ', 'NW': 'AV', 'OD': 'CB', 'OS': 'JP',
        'OL': 'NO', 'PA': 'FP',
        'PH': 'US', 'X': 'US', 'PS': 'PM', 'PR': 'CP', 'RQ': 'RO', 'SO': 'BZ', 'RTS': 'RM', 'SN': 'CI', 'SA': 'BZ',
        'SP': 'JP', 'SE': 'AB',
        'SBI': 'SS', 'SI': 'SP', 'SS': 'CH', 'SZ': 'CH', 'ST': 'SS', 'SG': 'GR', 'PE': 'RM', 'SU': 'IJ', 'S': 'SW',
        'TWO': 'TT', 'TW': 'TT',
        'TA': 'IT', 'BK': 'TB', 'T': 'JP', 'K': 'CN', 'TO': 'CN', 'VA': 'SM', 'VI': 'AV',
        'WA': 'PW', 'AD': 'AB', 'CA': 'EY', 'I': 'ID', 'IC': 'IR', 'AT': 'GA',
        'DE': 'GY'}

REGION_MAPPING_DICT = {'Korea & Japan': 'Asia',
                       'Hong Kong': 'Asia', 'Taiwan & Singapore': 'Asia',
                       'Southeast Asia': 'Asia',
                       'Asia exotic': 'Asia',
                       'South Africa': 'South Africa',
                       'Americas': 'Americas',
                       'China': 'Asia', 'Australia': 'Asia', 'Turkey': 'Asia'}

MARKET_MAPPING_DICT = {'Japan': 'Korea & Japan', 'South Korea': 'Korea & Japan',
                        'Hong Kong': 'Hong Kong', 'China': 'China', 'Turkey': 'Turkey',
                        'Taiwan': 'Taiwan & Singapore', 'Singapore': 'Taiwan & Singapore',
                        'Malaysia': 'Southeast Asia', 'Indonesia': 'Southeast Asia', 'Philipines': 'Southeast Asia', 'Thailand': 'Southeast Asia', 'Philippines': 'Southeast Asia',
                        'United States': 'Americas', 'Canada': 'Americas',
                        'South Africa': 'South Africa'}